name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Jar
        run: gradlew.bat clean build -x test

      - name: Create EXE
        run: |
          jpackage ^
            --type app-image ^
            --name FontTool ^
            --input lib\build\libs ^
            --main-jar font-tool-1.0.jar ^
            --dest dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FontTool
          path: dist